package com.vivotek.myprototype.common

const val PRIVILEGE_CHANGED: String = "privilege_changed"
const val RESOURCE_NOT_FOUND: String = "resource_not_found"

class IntentParam {
    companion object {
        const val siteID: String = "siteID"
        const val instant: String = "instant"
        const val messageDetail: String = "messageDetail"
        const val accessDetail: String = "accessDetail"
        const val sensorDetail: String = "sensorDetail"
        const val accessDetailPageNumber: String = "accessDetailPageNumber"
        const val sensorDetailPageNumber: String = "sensorDetailPageNumber"
        const val pushNotificationInfo: String = "pushNotificationInfo"
        const val multiChannelsInfo: String = "multiChannelsInfo"
        const val archiveID: String = "archiveID"
        const val messageTab: String = "messageTab"
        const val messageFilter: String = "messageFilter"
        const val url: String = "url"
        const val escapeUrlPattern: String = "escapeUrlPattern"
        const val siteName: String = "siteName"
        const val deviceName: String = "deviceName"
        const val deviceCity: String = "deviceCity"
        const val country: String = "country"
        const val dataSelectType: String = "dataSelectType"
        const val selectedMainViewTab: String = "selectedMainViewTab"
        const val startBy: String = "startBy"
        const val devicePK: String = "devicePK"
        const val pickOnly: String = "editOnly"
        const val deepSearchFilter: String = "deepSearchFilter"
        const val uuid: String = "uuid"
        const val eventInsightFilter: String = "eventInsightFilter"
        const val deleteType: String = "deleteType"
        const val startFrom: String = "startFrom"
        const val quality: String = "quality"
        const val profileSearchResultIndex: String = "profileSearchResultIndex"
        const val bindingDoors: String = "bindingDoor"
        const val selectedDoorIndex: String = "selectDoorIndex"
        const val provider: String = "provider"
        const val actionType: String = "actionType"
        const val pending: String = "pending"
        const val ssoLoginErrorType: String = "ssoLoginErrorType"
        const val eventType: String = "eventType"
        const val ruleName: String = "ruleName"
        const val messageType: String = "messageType"
        const val scenarioType: String = "scenarioType"
        const val startDestination: String = "startDestination"
        const val customizedViewId: String = "customizedViewId"
        const val bottomTabs: String = "bottomTabs"
        const val hideOperation: String = "hideOperation"
        const val floorPlan: String = "floorPlan"
        const val floorPlanSites: String = "floorPlanSites"
        const val disconnectOdysseyOnDestroy: String = "disconnectOdysseyOnDestroy"
        const val serviceMaintenance: String = "serviceMaintenance"
        const val eventID: String = "eventID"
    }
}